name: EAS Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js Environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Dependencies in Frontend
      - name: Install Dependencies
        run: |
          cd App/Pot-Hole-Detector-Frontend
          npm install

      # Step 4: Install EAS CLI Globally
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Step 5: Authenticate with Expo
      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas login --token $EXPO_TOKEN

      # Step 6: Trigger EAS Build for Android
      - name: Trigger EAS Build
        id: trigger_build
        run: |
          cd App/Pot-Hole-Detector-Frontend
          BUILD_OUTPUT=$(eas build --platform android --profile production --non-interactive --json)
          echo "$BUILD_OUTPUT"
          # Extract Build ID from EAS CLI output using jq
          BUILD_ID=$(echo "$BUILD_OUTPUT" | jq -r '.[0].id')
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV

      # Step 7: Wait for Build Completion
      - name: Wait for Build Completion
        run: |
          cd App/Pot-Hole-Detector-Frontend
          echo "Waiting for build to complete..."
          while true; do
            STATUS=$(eas build:inspect --platform android --id $BUILD_ID --json | jq -r '.[0].status')
            echo "Build Status: $STATUS"
            if [[ "$STATUS" == "finished" ]]; then
              echo "Build completed successfully."
              break
            elif [[ "$STATUS" == "errored" ]]; then
              echo "Build failed."
              exit 1
            else
              echo "Build in progress. Waiting for 60 seconds..."
              sleep 60
            fi
          done

      # Step 8: Fetch Build Artifacts (APK URL)
      - name: Fetch Build Artifacts
        run: |
          cd App/Pot-Hole-Detector-Frontend
          BUILD_URL=$(eas build:inspect --platform android --id $BUILD_ID --json | jq -r '.[0].artifacts.android.apk.url')
          echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV

      # Step 9: Download the APK
      - name: Download APK
        run: |
          wget $BUILD_URL -O PotHole-${GITHUB_REF_NAME}.apk

      # Step 10: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated build for ${{ github.ref }}
          draft: false
          prerelease: false

      # Step 11: Upload APK to GitHub Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PotHole-${GITHUB_REF_NAME}.apk
          asset_name: PotHole-${GITHUB_REF_NAME}.apk
          asset_content_type: application/vnd.android.package-archive
